### ISSUE TITLE
Implement user id and setup private routes

### ISSUE THREAD

**Issue by chrismolina159** [nyu-software-engineering/spring-2020-basic-thunder#68]
This is part of user story #7 

Upon logging in/signing up, a user should have some id attached(this can be hard coded in since we don't have database integration yet), so that all the pages they view are for themselves.

Later we will have to implement an authentication that only the user with this ID can view the specific url

**Comment by szwalker** [comment]
This task has been revoked because we will use the JWT authentication mechanism.
